NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. 

# 1. Array Creation


#####There are 6 general mechanisms for creating arrays:

Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

In [4]:
import numpy as np

In [5]:
a1D = np.array([10,11, 23, 2,33, 12])
a2D = np.array([[7, 2], [8, 4]])
a3D = np.array([[9, 2], [2, 4], [11, 6]])   ### multi-dimensional.............
a1D,a2D, a3D

(array([10, 11, 23,  2, 33, 12]),
 array([[7, 2],
        [8, 4]]),
 array([[ 9,  2],
        [ 2,  4],
        [11,  6]]))

In [11]:
a=np.arange(6)
b= a[np.newaxis,: ]
b, b.shape

(array([[0, 1, 2, 3, 4, 5]]), (1, 6))

In [10]:
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

In [11]:
a = np.array([127, 128, 129], dtype=np.uint8)
a

array([127, 128, 129], dtype=uint8)

In [12]:
a = np.array([127, 128, 129], dtype=np.uint32)
a

array([127, 128, 129], dtype=uint32)

In [13]:
np.empty([2, 2], int)

array([[        0,         0],
       [837407168,       564]])

# 1.2 Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

# 1.3 Replicating, joining, or mutating existing arrays

# 1.4 Reading arrays from disk, either from standard or custom formats

# 1.5 Creating arrays from raw bytes through the use of strings or buffers

# 1.6 Use of special library functions (e.g., random)