In [1]:
import numpy as ali
array=ali.array([1, 2, 3, 4, 5, 6, 7, 8, 9,])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop

In [45]:
#Random number generator
#--------------------------------
array1=ali.random.randn(1,50)  #randn() gives single number
array2=ali.arange(100)  # or (1, 100)

ar3=ali.linspace(2, 100, 50) #numpy.arange is to use integer start, end, and step values(total step 50)

array1, array2, ar3

(array([[ 0.3932425 , -0.30879647,  1.00297941, -2.32922058, -0.98857393,
          1.2409504 , -0.569235  , -0.4467096 ,  0.3256026 ,  0.75941885,
          0.61365672,  1.48884044,  1.10062684, -1.21489879,  1.18701716,
          1.40001285,  0.60705801,  0.33963565,  0.89025081, -0.87804207,
          0.84091511, -2.32061907,  0.32203843,  0.01936755,  0.37738218,
         -0.72764308, -0.04284242, -0.47505175, -0.58497611, -0.88163109,
          0.28237376,  0.81076522,  0.26392299,  0.19010567, -0.57579062,
          1.19965244,  0.22773453, -1.44567982, -0.30430762, -1.02712742,
         -0.63539309,  0.98879634, -0.8824798 , -0.39349864,  2.04171356,
          0.89190653, -1.66969676, -1.20171072, -0.07315431, -0.29678679]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 5

NumPy clip()
NumPy log()
NumPy exp()
NumPy round()
NumPy sum()
NumPy power()
NumPy cumsum()
NumPy multiply()
NumPy sqrt()
NumPy floor()
NumPy absolute()
NumPy diff()
NumPy divide()
NumPy sine()
NumPy square()
NumPy add()
NumPy minimum()
NumPy maximum()
NumPy arctan2()
NumPy cross()
NumPy sign()
NumPy log10()
NumPy arctan()
NumPy amax()
NumPy arccos()
NumPy cosine()
NumPy amin()
NumPy subtract()
NumPy trapz()
NumPy ceil()
NumPy arcsin()
NumPy product()
NumPy tanh()
NumPy around()
NumPy hypot()
NumPy tangent()

In [53]:
np =ali.log(array)
array,np


(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458]))

In [61]:
n=ali.clip(array2, 1, 200) # gives within range, otherwise max for else
#The clip() function is used to limit the values in an array to a specified range
n

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
e=ali.exp(array)
e

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [72]:
exponent=3
p=ali.power(array,exponent)
p

array([  1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [73]:
r=ali.round(array1)
r

array([[ 0., -0.,  1., -2., -1.,  1., -1., -0.,  0.,  1.,  1.,  1.,  1.,
        -1.,  1.,  1.,  1.,  0.,  1., -1.,  1., -2.,  0.,  0.,  0., -1.,
        -0., -0., -1., -1.,  0.,  1.,  0.,  0., -1.,  1.,  0., -1., -0.,
        -1., -1.,  1., -1., -0.,  2.,  1., -2., -1., -0., -0.]])

In [76]:
s=ali.sqrt(array1)
s   # minus value gives Nan

C:\Users\mdram\AppData\Local\Temp\ipykernel_9976\2753436979.py:1: RuntimeWarning: invalid value encountered in sqrt
  s=ali.sqrt(array1)


array([[0.6270905 ,        nan, 1.0014886 ,        nan,        nan,
        1.11397953,        nan,        nan, 0.57061599, 0.87144641,
        0.78336244, 1.2201805 , 1.04910764,        nan, 1.08950317,
        1.18322139, 0.77913928, 0.58278268, 0.94353103,        nan,
        0.91701424,        nan, 0.5674843 , 0.13916736, 0.6143144 ,
               nan,        nan,        nan,        nan,        nan,
        0.53138852, 0.90042502, 0.51373436, 0.43601109,        nan,
        1.09528647, 0.47721539,        nan,        nan,        nan,
               nan, 0.99438239,        nan,        nan, 1.42888543,
        0.94440803,        nan,        nan,        nan,        nan]])

In [77]:
a=ali.arctan(array)
a

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077,
       1.40564765, 1.42889927, 1.44644133, 1.46013911])

In [78]:
f=ali.floor(array1)
f

array([[ 0., -1.,  1., -3., -1.,  1., -1., -1.,  0.,  0.,  0.,  1.,  1.,
        -2.,  1.,  1.,  0.,  0.,  0., -1.,  0., -3.,  0.,  0.,  0., -1.,
        -1., -1., -1., -1.,  0.,  0.,  0.,  0., -1.,  1.,  0., -2., -1.,
        -2., -1.,  0., -1., -1.,  2.,  0., -2., -2., -1., -1.]])

In [ ]:
m=ali.max()

-#------------------------------------------------




#########################################